/**
 * Export to PDF — print-ready HTML endpoint
 * Generates a clean, self-contained HTML page with embedded CSS
 * that can be printed to PDF by the browser or client-side library (jsPDF).
 *
 * Route: GET /export/pdf/:tableId
 */
import { Hono } from 'hono'
import {
  PDF_CSS,
  escHtml,
  buildRowsHtml,
  buildWeightsHtml,
  buildCouncilHtml,
  buildLegendHtml
} from './pdf-styles.js'

export const exportPdfRoutes = new Hono()

exportPdfRoutes.get('/export/pdf/:tableId', async (c) => {
  const db = c.get('db')
  const tableId = c.req.param('tableId')

  // ─── Load table metadata ───
  const table = db.prepare('SELECT * FROM tables WHERE id = ?').get(tableId)
  if (!table) {
    return c.json({ error: 'Table not found' }, 404)
  }

  // ─── Load columns definition ───
  const columnsRow = db.prepare('SELECT definition FROM columns WHERE table_id = ?').get(tableId)
  const columns = columnsRow?.definition ? JSON.parse(columnsRow.definition) : []

  // ─── Load rows ───
  const rawRows = db.prepare('SELECT * FROM rows WHERE table_id = ?').all(tableId)
  const rows = rawRows.map(r => {
    const data = typeof r.data === 'string' ? JSON.parse(r.data) : r.data
    return {
      ...data,
      _tco_1y: r.tco_1y,
      _tco_3y: r.tco_3y,
      _tco_5y: r.tco_5y,
      _currency: r.currency
    }
  })

  // ─── Sort rows by utility (descending) ───
  rows.sort((a, b) => (b.utility || 0) - (a.utility || 0))

  // ─── Load council decision if exists ───
  let councilDecision = null
  try {
    const cd = db.prepare(
      "SELECT * FROM council_decisions WHERE table_id = ? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1"
    ).get(tableId)
    if (cd) {
      councilDecision = {
        topic: cd.topic,
        consensus: cd.consensus,
        editorSummary: cd.editor_summary,
        votes: cd.votes
      }
    }
  } catch { /* table may not exist */ }

  // ─── Generate HTML ───
  const html = buildHtml(table, columns, rows, councilDecision)

  const filename = encodeURIComponent(`${table.title || tableId}.pdf`)
  c.header('Content-Type', 'text/html; charset=utf-8')
  c.header('Content-Disposition', `inline; filename="${filename}"`)
  c.header('Cache-Control', 'no-cache')

  return c.body(html)
})

// ─── Build full HTML document ───
function buildHtml(table, columns, rows, councilDecision) {
  const title = escHtml(table.title || 'Decision Table')
  const description = escHtml(table.description || '')
  const maxUtility = Math.max(...rows.map(r => r.utility || 0), 1)
  const exportDate = new Date().toLocaleString()

  // Only columns with weight > 0 (criteria) + name column
  const criteriaColumns = columns.filter(c => (c.weight || 0) > 0)

  // Build HTML parts via extracted helpers
  const rowsHtml = buildRowsHtml(rows, criteriaColumns, maxUtility)
  const weightsHtml = buildWeightsHtml(criteriaColumns)
  const councilHtml = buildCouncilHtml(councilDecision)
  const legendHtml = buildLegendHtml()

  // ─── Assemble full HTML ───
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} — Choser EDP</title>
  <style>
${PDF_CSS}
  </style>
</head>
<body>

  <button class="print-btn no-print" onclick="window.print()">📄 Save as PDF</button>

  <!-- Header -->
  <div class="header">
    <h1>${title}</h1>
    ${description ? `<div class="description">${description}</div>` : ''}
    <div class="meta">
      <span class="badge badge-choser">Choser EDP</span>
      <span class="badge badge-date">Exported: ${exportDate}</span>
      ${rows.length ? `<span class="badge badge-date">${rows.length} alternatives</span>` : ''}
      ${criteriaColumns.length ? `<span class="badge badge-date">${criteriaColumns.length} criteria</span>` : ''}
    </div>
  </div>

  ${rows.length > 0 ? `
  <!-- Data Table -->
  <div class="section">
    <h2>📊 Comparison Table</h2>
    <table class="data-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          ${criteriaColumns.map(col => `<th>
            ${escHtml(col.title || col.key)}
            <br><span class="weight-header">w: ${col.weight || 0}%</span>
          </th>`).join('')}
          <th>Utility</th>
        </tr>
      </thead>
      <tbody>
        ${rowsHtml}
      </tbody>
    </table>

    ${legendHtml}
  </div>
  ` : '<div class="section"><p style="text-align:center;color:#9CA3AF;padding:30px;">No data rows in this table.</p></div>'}

  ${criteriaColumns.length > 0 ? `
  <!-- Criteria Weights -->
  <div class="section">
    <h2>⚖️ Criteria Weights</h2>
    <div class="weights-grid">
      ${weightsHtml}
    </div>
  </div>
  ` : ''}

  ${councilHtml}

  <!-- Footer -->
  <div class="footer">
    Generated by <strong>Choser EDP</strong> — Enterprise Decision Platform &nbsp;|&nbsp; ${exportDate}
  </div>

</body>
</html>`
}
